name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '5.5'
                      dependency-versions: 'lowest'
                      tools: 'composer:v1'
                      env:
                          SYMFONY__DEPRECATIONS__HELPER: disabled

                    - php-version: '7.4'
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY__DEPRECATIONS__HELPER: weak

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: ${{ matrix.tools }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{matrix.dependency-versions}}

            - name: Lint code
              run: composer validate --strict

            - name: Run tests
              run: time vendor/bin/phpunit
              env: ${{ matrix.env }}
